import DefaultNavbar from './components/Navbar'
import './globals.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: {
  children: React.ReactNode
}) {
	return (
		<html lang="pt-br" className='dark'>
			<body className='bg-gray-900 h-screen flex flex-col'>
				<DefaultNavbar/>
				{children}
			</body>
		</html>
	)
}
